# Properties of Dot Product - Lab

## Introduction

In this lab we shall look at some interesting properties of a Dot product type matrix multiplication. Understanding these properties will become useful as we move forward with machine learning advanced linear algebra. The lab will require you to calculate results to provide a proof for these properties.

## Objectives
You will be able to:
* Understand and analytically explain Distributive, Commutative and Associative properties of dot product

## Instructions

* For each property, create suitably sized matrices with random data and prove the equations 
* Ensure that size/dimension assumptions are met while performing calculations (you'll see errors otherwise)
* Calculate the LHS and RHS for all equations and show if they are equal or not

## Distributive Property - Matrices multiplication is distributive
### Prove that A.(B+C)=A.B+A.C

In [3]:
# Your code here
import numpy as np

A = np.random.randint(10, size=(3, 3))
B = np.random.randint(10, size=(3, 2))
C = np.random.randint(10, size=(3, 2))

LHS = A.dot((B+C))
RHS = A.dot(B) + A.dot(C)

print(LHS)
print(RHS)

[[142 134]
 [ 47  69]
 [214 241]]
[[142 134]
 [ 47  69]
 [214 241]]


## Associative Property - Matrices multiplication is associative
### Prove that A.(B.C)=(A.B).C

In [6]:
# Your code here 

A = np.random.randint(10, size=(3, 3))
B = np.random.randint(10, size=(3, 3))
C = np.random.randint(10, size=(3, 3))

LHS = A.dot(B.dot(C))
RHS = (A.dot(B)).dot(C)

print(LHS)
print(RHS)

[[ 547  160  286]
 [ 942  264  477]
 [1134  320  577]]
[[ 547  160  286]
 [ 942  264  477]
 [1134  320  577]]


## Commutative Property - Matrix multiplication is NOT commutative
### Prove that for matrices, A.B ≠ B.A

In [7]:
# Your code here 
A = np.random.randint(10, size=(3, 3))
B = np.random.randint(10, size=(3, 3))

LHS = A.dot(B)
print(LHS)

RHS = B.dot(A)
print(RHS)

[[ 63  44 121]
 [ 63  32  85]
 [  7  21  44]]
[[51 12 36]
 [56 12 76]
 [84 12 76]]


## Commutative Property -  vector multiplication IS commutative
### Prove that for vectors, x<sup>T</sup> . y = y<sup>T</sup> . x
Note: superscipt<sup>T</sup> denotes the transpose we saw earlier

In [11]:
# Your code here 
x = np.random.randint(10, size=(4))
y = np.random.randint(10, size=(4))

LHS = (x.T).dot(y)
RHS = (y.T).dot(x)
print(x, LHS)
print(y,RHS)

print(LHS)
print(RHS)

[0 4 0 0] 8
[6 2 9 1] 8
8
8


#### and finally 
## Simplification of the matrix product
### Prove that  (A.B)<sup>T</sup> = B<sup>T</sup> . A<sup>T</sup>

In [14]:
# Your code here 
A = np.random.randint(10, size=(3, 3))
B = np.random.randint(10, size=(3, 3))

LHS = (A.dot(B)).T
RHS = (B.T).dot((A.T))

print(A)
print(B)
print(LHS,RHS)
print(LHS==RHS)


[[4 5 9]
 [6 3 1]
 [0 1 3]]
[[1 3 9]
 [8 3 5]
 [8 8 9]]
[[116  38  32]
 [ 99  35  27]
 [142  78  32]] [[116  38  32]
 [ 99  35  27]
 [142  78  32]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


## Summary 

So now we have seen enough matrix algebra to help us solve a problem of linear equations as we saw earlier in this section. We shall see how to do this next. 